"""Add website and other fields to Venue

Revision ID: 6e2f9b14ef89
Revises: fa6d1d0840ab
Create Date: 2024-06-11 13:24:32.397662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2f9b14ef89'
down_revision = 'fa6d1d0840ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.drop_column('needs_venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('website')
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
