"""Move needs_talent from Artist to Venue

Revision ID: f16ee1255f78
Revises: 5c1c0f0355bf
Create Date: 2024-06-11 11:59:14.042265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16ee1255f78'
down_revision = '5c1c0f0355bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('needs_talent')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_talent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('needs_talent')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
